### ISSUE TITLE
Reference and Output (signal) tensor size mismatch when computing STOI.

### ISSUE THREAD

**Issue by sangeet2020** [facebookresearch/denoiser#102]
Hello Authors,
 Let me start with appreciating and thanking for this work and having it opensource.

I am trying to train the model on the valentini dataset (all audio downsampled to 16K), just to reproduce the results. But after around 10 epochs, I get this error:
```
------------
[2021-12-27 15:40:00,034][denoiser.solver][INFO] - Evaluating on the test set...
[2021-12-27 15:40:05,117][denoiser.evaluate][INFO] - Eval estimates | 82/412 | 16.7 it/sec
[2021-12-27 15:40:09,529][denoiser.evaluate][INFO] - Eval estimates | 164/412 | 17.6 it/sec
[2021-12-27 15:40:14,164][denoiser.evaluate][INFO] - Eval estimates | 246/412 | 17.6 it/sec
[2021-12-27 15:40:18,717][denoiser.evaluate][INFO] - Eval estimates | 328/412 | 17.7 it/sec
[2021-12-27 15:40:23,405][denoiser.evaluate][INFO] - Eval estimates | 410/412 | 17.7 it/sec
[2021-12-27 15:40:23,488][denoiser.evaluate][INFO] - Eval metrics | 82/412 | 188584.6 it/sec
[2021-12-27 15:40:23,489][denoiser.evaluate][INFO] - Eval metrics | 164/412 | 102330.4 it/sec
[2021-12-27 15:40:23,714][__main__][ERROR] - Some error happened
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
File "/netscratch/sagar/miniconda/envs/denoiser2/lib/python3.7/concurrent/futures/process.py", line 239, in_process_worker
r = call_item.fn(*call_item.args, **call_item.kwargs)
File "/home/sagar/talking-robots/denoiser/denoiser/evaluate.py", line 98, in _run_metrics
stoi_i = get_stoi(clean, estimate, sr=sr)
File "/home/sagar/talking-robots/denoiser/denoiser/evaluate.py", line 126, in get_stoi
stoi_val += stoi(ref_sig[i], out_sig[i], sr, extended=False)
File "/netscratch/sagar/miniconda/envs/denoiser2/lib/python3.7/site-packages/pystoi/stoi.py", line 50, in stoi
'found {} and {}'.format(x.shape, y.shape))
Exception: x and y should have the same length,found (54711,) and (21838,)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "train.py", line 108, in main
_main(args)
File "train.py", line 102, in _main
run(args)
File "train.py", line 83, in run
solver.train()
File "/home/sagar/talking-robots/denoiser/denoiser/solver.py", line 174, in train
pesq, stoi = evaluate(self.args, self.model, self.tt_loader)
File "/home/sagar/talking-robots/denoiser/denoiser/evaluate.py", line 75, in evaluate
pesq_i, stoi_i = pending.result()
File "/netscratch/sagar/miniconda/envs/denoiser2/lib/python3.7/concurrent/futures/_base.py", line 428, in result
return self.__get_result()
File "/netscratch/sagar/miniconda/envs/denoiser2/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
raise self._exception
Exception: x and y should have the same length,found (54711,) and (21838,)
```
I do not understand, why is there is a tensor size mismatch when computing STOI.
Is there something, I am doing wrong? If anyone could help, I would really appreciate it.

PS; I frist tried training the model on the debug dataset and it was successful. 

Thank You

**Comment by adefossez** [comment]
The most likely cause is that there is an entry for which the noisy and clean wavs on disk have different sizes. You can check the generated jsons for the test set to see if some matching files have different sizes.

**Comment by sangeet2020** [comment]
Voila, you are absolutely right. I pointed out the corrupted sample and removed it. Thank You very much.
