### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by Ananyapam7** [facebookresearch/denoiser#112]
I ran the `python train.py` in the quickstart example and I got this-

```[2022-02-10 10:51:28,001][__main__][INFO] - For logs, checkpoints and samples check /home/ananyapam/Projects/Skit/denoiser/outputs/exp_
[2022-02-10 10:51:28,418][__main__][ERROR] - Some error happened
Traceback (most recent call last):
  File "train.py", line 105, in main
    _main(args)
  File "train.py", line 99, in _main
    run(args)
  File "train.py", line 25, in run
    from denoiser.solver import Solver
  File "/home/ananyapam/Projects/Skit/denoiser/denoiser/solver.py", line 19, in <module>
    from .evaluate import evaluate
  File "/home/ananyapam/Projects/Skit/denoiser/denoiser/evaluate.py", line 14, in <module>
    from pesq import pesq
  File "/home/ananyapam/anaconda3/envs/denoiser/lib/python3.7/site-packages/pesq/__init__.py", line 6, in <module>
    from .cypesq import cypesq, cypesq_retvals, cypesq_error_message as pesq_error_message
  File "pesq/cypesq.pyx", line 1, in init cypesq
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject```

**Comment by adefossez** [comment]
You probably need to reinstall peqs: `pip install -U git+https://github.com/ludlows/python-pesq#egg=pesq`
