### ISSUE TITLE
No documented setup works

### ISSUE THREAD

**Issue by jhkonan** [facebookresearch/denoiser#118]
None of these setups work for me. I am currently interested in denoising audio, but may want to train in the future.

**Setup 1:**
```
conda create -n demucs python=3.7
conda activate demucs
git clone https://github.com/facebookresearch/denoiser.git
cd denoiser
pip install -r requirements_cuda.txt
```
Results in the following issue:
```
ERROR: Could not find a version that satisfies the requirement torch==1.5.1+cu101 (from versions: 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0)
ERROR: No matching distribution found for torch==1.5.1+cu101
```
Note: If you try to hack around this by doing `conda install pytorch==1.5.1 torchvision==0.6.1 cudatoolkit=10.1 -c pytorch` and then commenting out the pytorch requirements, it will ask you to install julius. If you install julius and the other requirements in requirements.txt, you still end up with the same issue observed in Setup 2 or Setup 3.

**Setup 2:**
```
conda create -n demucs python=3.7
conda activate demucs
git clone https://github.com/facebookresearch/denoiser.git
cd denoiser
pip install -r requirements.txt
```
The pip install runs successfully. However, using the denoiser does not work.

```
~/anaconda3/envs/demucs/bin/python3 \
    -m denoiser.enhance \
    --model_path=/home/Downloads/dns64-a7761ff99a7d5bb6.th \
    --noisy_dir=/media/DNS/dns-2020-60k/wav/00-10/noisy \
    --out_dir=/media/DNS/dns-2020-60k/wav/00-10/demucs
```

Results in the following issue:
```
INFO:denoiser.pretrained:Loading model from /home/Downloads/dns64-a7761ff99a7d5bb6.th
Traceback (most recent call last):
  File "/home/anaconda3/envs/demucs/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/anaconda3/envs/demucs/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/denoiser/denoiser/enhance.py", line 155, in <module>
    enhance(args, local_out_dir=args.out_dir)
  File "/media/denoiser/denoiser/enhance.py", line 113, in enhance
    model = pretrained.get_model(args).to(args.device)
  File "/media/denoiser/denoiser/pretrained.py", line 72, in get_model
    model = deserialize_model(pkg)
  File "/media/denoiser/denoiser/utils.py", line 38, in deserialize_model
    klass = package['class']
KeyError: 'class'
```

**Setup 3:**
```
conda create -n demucs python=3.7
conda activate demucs
pip install denoiser
```
The pip install runs successfully. However, using the denoiser does not work.

```
~/anaconda3/envs/demucs/bin/python3 \
    -m denoiser.enhance \
    --model_path=/home/Downloads/dns64-a7761ff99a7d5bb6.th \
    --noisy_dir=/media/DNS/dns-2020-60k/wav/00-10/noisy \
    --out_dir=/media/DNS/dns-2020-60k/wav/00-10/demucs
```
Results in the following issue:
```
INFO:denoiser.pretrained:Loading model from /home/deepology/Downloads/dns64-a7761ff99a7d5bb6.th
Traceback (most recent call last):
  File "/home/anaconda3/envs/demucs/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/anaconda3/envs/demucs/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/anaconda3/envs/demucs/lib/python3.7/site-packages/denoiser/enhance.py", line 155, in <module>
    enhance(args, local_out_dir=args.out_dir)
  File "/home/anaconda3/envs/demucs/lib/python3.7/site-packages/denoiser/enhance.py", line 113, in enhance
    model = pretrained.get_model(args).to(args.device)
  File "/home/anaconda3/envs/demucs/lib/python3.7/site-packages/denoiser/pretrained.py", line 65, in get_model
    model = deserialize_model(pkg)
  File "/home/anaconda3/envs/demucs/lib/python3.7/site-packages/denoiser/utils.py", line 35, in deserialize_model
    klass = package['class']
KeyError: 'class'
```

Am I missing something, or are none of these setups currently working?

**Comment by jhkonan** [comment]
I am also using this model (dns64):
https://dl.fbaipublicfiles.com/adiyoss/denoiser/dns64-a7761ff99a7d5bb6.th

**Comment by jhkonan** [comment]
dns64 flag downloads model but does not change behavior.

Generating the json using denoiser.audio does not change the observed error.

**Comment by jhkonan** [comment]
After using the --dns64 or --dns48 flag, we see an error like this:

```
INFO:denoiser.pretrained:Loading pre-trained real time H=48 model trained on DNS.
WARNING:__main__:Small sample set was not provided by either noisy_dir or noisy_json. Skipping enhancement.
```

**Comment by adefossez** [comment]
you are passing `--noisy_dir=/media/DNS/dns-2020-60k/wav/00-10/noisy.json` but this should be `--noisy_json =/media/DNS/dns-2020-60k/wav/00-10/noisy.json`

**Comment by jhkonan** [comment]
Both of these approaches do not work:

```
!~/anaconda3/envs/demucs/bin/python3 \
    -m denoiser.enhance \
    --device cuda \
    --model_path=/home/.cache/torch/hub/checkpoints/dns64-a7761ff99a7d5bb6.th \
    --noisy_json=/media/DNS/dns-2020-60k/wav/enhan_00_10.json \
    --out_dir=/media/data2/DNS/dns-2020-60k/wav/00-10/demucs
```


```
!~/anaconda3/envs/demucs/bin/python3 \
    -m denoiser.enhance \
    --device cuda \
    --model_path=/home/.cache/torch/hub/checkpoints/dns64-a7761ff99a7d5bb6.th \
    --noisy_dir=/media/DNS/dns-2020-60k/wav/00-10/noisy \
    --out_dir=/media/DNS/dns-2020-60k/wav/00-10/demucs
```

**Comment by jhkonan** [comment]
I was able to get the cpu specification from source working with the --dns64 flag.
