### ISSUE TITLE
KeyError: 'model' when trying to continue from a previously trained model 'best.th'

### ISSUE THREAD

**Issue by youssefavx** [facebookresearch/denoiser#39]
Yesterday I fine tuned dns64 on 32kHz on Colab. I exported the best.th model file to google, and then tested it, it worked fine. However, I wanted to continue training from this model's point. So I set the config file setting `continue_from` to `/content/drive/MyDrive/best.th`

Then when running, I got this error: 

```
[2021-01-11 03:50:57,731][denoiser.solver][INFO] - Loading checkpoint model: /content/drive/MyDrive/best.th
[2021-01-11 03:50:59,057][__main__][ERROR] - Some error happened
Traceback (most recent call last):
  File "train.py", line 104, in main
    _main(args)
  File "train.py", line 98, in _main
    run(args)
  File "train.py", line 78, in run
    solver = Solver(data, model, optimizer, args)
  File "/content/denoiser/denoiser/solver.py", line 70, in __init__
    self._reset()
  File "/content/denoiser/denoiser/solver.py", line 111, in _reset
    self.model.load_state_dict(package['model']['state'])
KeyError: 'model'
```

Would love any help whatsoever. It'd be really cool if I could continue training from a previous checkpoint since Colab doesn't give continuous access.

**Comment by adefossez** [comment]
You should point to the `checkpoint.th` file, no the `best.th` file, and pass `continue_best=true`. Loading directly from the `best.th` file is not supported here, sorry about that!

**Comment by youssefavx** [comment]
Thank you so much! I'll try this tomorrow and will report back.

**Comment by youssefavx** [comment]
And it's working! So so happy about this, can't thank you enough!
