### ISSUE TITLE
solver.py:211: UserWarning: Using a target size (torch.Size([1, 1, 112543])) that is different to the input size (torch.Size([1, 1, 112499])).

### ISSUE THREAD

**Issue by youssefavx** [facebookresearch/denoiser#47]
In the config yaml file I set `depth` to `6` and `hidden` to `96`, and I got this error during cross-validation (training was going fine up til then):

```
[2021-02-05 00:17:19,682][__main__][INFO] - For logs, checkpoints and samples check /content/drive/My Drive/outputs/exp_demucs.hidden=96
[2021-02-05 00:17:26,292][denoiser.solver][INFO] - ----------------------------------------------------------------------
[2021-02-05 00:17:26,292][denoiser.solver][INFO] - Training...
[2021-02-05 00:39:43,596][denoiser.solver][INFO] - Train | Epoch 1 | 822/4114 | 0.6 it/sec | Loss 0.00932
[2021-02-05 01:02:00,280][denoiser.solver][INFO] - Train | Epoch 1 | 1644/4114 | 0.6 it/sec | Loss 0.00815
[2021-02-05 01:24:16,911][denoiser.solver][INFO] - Train | Epoch 1 | 2466/4114 | 0.6 it/sec | Loss 0.00757
[2021-02-05 01:46:33,454][denoiser.solver][INFO] - Train | Epoch 1 | 3288/4114 | 0.6 it/sec | Loss 0.00715
[2021-02-05 02:08:49,911][denoiser.solver][INFO] - Train | Epoch 1 | 4110/4114 | 0.6 it/sec | Loss 0.00687
[2021-02-05 02:08:56,199][denoiser.solver][INFO] - Train Summary | End of Epoch 1 | Time 6689.91s | Train Loss 0.00686
[2021-02-05 02:08:56,200][denoiser.solver][INFO] - ----------------------------------------------------------------------
[2021-02-05 02:08:56,200][denoiser.solver][INFO] - Cross validation...
/content/denoiser/denoiser/solver.py:211: UserWarning: Using a target size (torch.Size([1, 1, 112543])) that is different to the input size (torch.Size([1, 1, 112499])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss = F.l1_loss(clean, estimate)
[2021-02-05 02:09:00,276][__main__][ERROR] - Some error happened
Traceback (most recent call last):
  File "train.py", line 104, in main
    _main(args)
  File "train.py", line 98, in _main
    run(args)
  File "train.py", line 79, in run
    solver.train()
  File "/content/denoiser/denoiser/solver.py", line 148, in train
    valid_loss = self._run_one_epoch(epoch, cross_valid=True)
  File "/content/denoiser/denoiser/solver.py", line 211, in _run_one_epoch
    loss = F.l1_loss(clean, estimate)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 2190, in l1_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/usr/local/lib/python3.6/dist-packages/torch/functional.py", line 52, in broadcast_tensors
    return torch._C._VariableFunctions.broadcast_tensors(tensors)
RuntimeError: The size of tensor a (112499) must match the size of tensor b (112543) at non-singleton dimension 2
```

I wonder if this is related to my settings or something else. `batch size` was set to `6`

**Comment by youssefavx** [comment]
Just in case anybody else comes across the problem, I know it's not much of a solution but for now, I've just removed the cross validation dataset and test dataset from my config file and set eval every to a very high number. It's training fine so far.

**Comment by adefossez** [comment]
This is quite weird, normally the denoiser model should always return a tensor of the exact same size.
Are you using a custom dataset? You probably have a noisy and clean file of different lengths in your valid set.

**Comment by youssefavx** [comment]
Thank you for the hint!

That's a good point I should probably test with a debugging dataset first to make sure that is not the case. 

I do have a custom dataset that I make on the spot (Colab) by downloading the Valentini dataset and mixing them with my own kinds of noise. 

I have a function that copies the clean audio file, and a function that combines the noise with the clean audio file. 

I've made sure to make the clean function cut the clean audio file by the same length as the noisy file (since I know they have to be exactly the same). 

But I will try to double check the sizes of the validation dataset and report back.

**Comment by adefossez** [comment]
sounds good, from the code, I would try to add a print statement when cross_valid is True, showing the size of the ground truth, noisy and estimate (`clean.shape, noisy.shape, estimate.shape`) just to see if something is wrong there.

**Comment by youssefavx** [comment]
Will try this out, thank you! It turns out, I double-checked the sizes and lengths and the lengths and sizes of the files are actually off by a very small margin. 

I guess pydub isn't as precise/deterministic as I thought it could be, or maybe I'm making a stupid mistake in the code.

The confusing part is it trains fine, and it uses the same function but maybe I'm misremembering. I'll try to examine further.

**Comment by adefossez** [comment]
At train time, the code uses fixed length frames over the data, so unless the difference is large it should work. At validation time, it separates entire files one at a time.

**Comment by youssefavx** [comment]
Makes sense! Thank you
