### ISSUE TITLE
KeyError: 'class'

### ISSUE THREAD

**Issue by youssefavx** [facebookresearch/denoiser#48]
No need to respond as I know I'm doing some weird experimental stuff here...

I trained a model with demucs.hidden set to 96, and a depth of 6. 

I downloaded the checkpoint.th which was around 4.5 GB. 

I ran a command to test it on an audio file, and I got this error:

```python
INFO:denoiser.pretrained:Loading model from /Volumes/Transcend/checkpoint_44K_96.th
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/denoiser/enhance.py", line 138, in <module>
    enhance(args, local_out_dir=args.out_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/denoiser/enhance.py", line 107, in enhance
    model = pretrained.get_model(args).to(args.device)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/denoiser/pretrained.py", line 62, in get_model
    pkg = torch.load(args.model_path, map_location='cuda:0')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/serialization.py", line 765, in _legacy_load
    result = unpickler.load()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/serialization.py", line 721, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/serialization.py", line 800, in restore_location
    return default_restore_location(storage, map_location)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/serialization.py", line 174, in default_restore_location
    result = fn(storage, location)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/serialization.py", line 150, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/serialization.py", line 134, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

So then I edited `pretrained.py`

I changed: 

```
pkg = torch.load(args.model_path)
```

to:

```
pkg = torch.load(args.model_path, map_location=torch.device('cpu'))
```

and I also tried:
```
pkg = torch.load(args.model_path, map_location='cpu')
```

And I get this error when I run the same command again:

```python
INFO:denoiser.pretrained:Loading model from /Volumes/Transcend/checkpoint_44K_96.th
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/denoiser/enhance.py", line 138, in <module>
    enhance(args, local_out_dir=args.out_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/denoiser/enhance.py", line 107, in enhance
    model = pretrained.get_model(args).to(args.device)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/denoiser/pretrained.py", line 65, in get_model
    model = deserialize_model(pkg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/denoiser/utils.py", line 39, in deserialize_model
    klass = package['class']
KeyError: 'class'
```

**Comment by adefossez** [comment]
Can you give me the exact commandline you are writing?

**Comment by adefossez** [comment]
Can you update the repo and try again? I should have fixed the issue now :)

**Comment by youssefavx** [comment]
Awesome! Thank you so much. I'll try!

**Comment by youssefavx** [comment]
I just tried it and it worked! I didn't know whether doing `pip install denoiser` would give me the latest commit or how to install the latest one, so I just made the same edit to `pretrained.py` and it worked.

Thanks again!

**Comment by TrieBr** [comment]
I still get this error even with the latest code
