### ISSUE TITLE
torch error loading checkpoint + best.th

### ISSUE THREAD

**Issue by youssefavx** [facebookresearch/denoiser#57]
This seems like a new development. After training a new model, and trying to run inference on my computer, I get this (new warning paired with the following error):

```python
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torchaudio/backend/utils.py:54: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  '"sox" backend is being deprecated. '
INFO:denoiser.pretrained:Loading model from /Users/yousseavx/Downloads/checkpoint.th
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/yousseavx/denoiser/denoiser/enhance.py", line 155, in <module>
    enhance(args, local_out_dir=args.out_dir)
  File "/Users/yousseavx/denoiser/denoiser/enhance.py", line 113, in enhance
    model = pretrained.get_model(args).to(args.device)
  File "/Users/yousseavx/denoiser/denoiser/pretrained.py", line 59, in get_model
    pkg = torch.load(args.model_path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/serialization.py", line 774, in _legacy_load
    result = unpickler.load()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/serialization.py", line 730, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/serialization.py", line 151, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/serialization.py", line 135, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

(This is in fact [with the new modification](https://github.com/facebookresearch/denoiser/commit/01cc7f8e48c6a2d272253aa91cd3d8e3053a7ce8) / updated code that solved the error a while back). So when I tried to modify the line:

```python
pkg = torch.load(args.model_path)
```

to:

```python
pkg = torch.load(args.model_path, map_location=torch.device('cpu'))
```

I now get this:

```
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torchaudio/backend/utils.py:54: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  '"sox" backend is being deprecated. '
INFO:denoiser.pretrained:Loading model from /Users/yousseavx/Downloads/best.th
```

But now the program just terminates in the terminal immediately after it prints that last line. And I've tried this with both the checkpoint.th model and best.th model. 

The model was dns48, training from scratch, training only without cross-validation or testing. 

I tried this with the `pip3 install -U denoiser` 

And I also tried running this same command from inside the current git cloned repo, same error / behavior.

**Comment by youssefavx** [comment]
After checking other models (dns64, and other previously trained models that used to work), this same behavior occurs for those models also so I don't think it's specific to the latest model I trained.

**Comment by adefossez** [comment]
can you try again with `--num_workers=1`

**Comment by youssefavx** [comment]
That worked! Thank you again!
