### ISSUE TITLE
Multiprocessing error with large number of files

### ISSUE THREAD

**Issue by HarisNaveed17** [facebookresearch/denoiser#89]
Hello, 
First of all great work, I tried out your dns64 model on some samples of my data and the results were impressive. 
However, I now want to run the model on my entire set. About 78,000 audio files between 6 to 53 seconds long, with an average length of 15 seconds. 

When I do that, I encounter the following error:
INFO:denoiser.pretrained:Loading pre-trained real time H=64 model trained on DNS.
Killed%
Process ForkProcess-10:
Process ForkProcess-4:
Process ForkProcess-2:
Traceback (most recent call last):
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/concurrent/futures/process.py", line 233, in _process_worker
    call_item = call_queue.get(block=True)
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/connection.py", line 620, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/concurrent/futures/process.py", line 233, in _process_worker
    call_item = call_queue.get(block=True)
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/connection.py", line 620, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/concurrent/futures/process.py", line 233, in _process_worker
    call_item = call_queue.get(block=True)
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/connection.py", line 620, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/concurrent/futures/process.py", line 233, in _process_worker
    call_item = call_queue.get(block=True)
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
  File "/home/haris/miniconda3/envs/denoiser/lib/python3.7/multiprocessing/connection.py", line 620, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

I understand the problem may be due to some synchronization issue, but I'm not sure how to solve it. I did make it run eventually by setting num_workers=1, but the processing is really slow. About 16,000 after running for an entire day. 

Any advice or further reading references are appreciated. Thank you!

**Comment by adefossez** [comment]
Hello @HarisNaveed17 
Did you try setting it to a low number of workers like `num_workers=2` ?
How much RAM do you have ?

**Comment by HarisNaveed17** [comment]
@adefossez yes I even set it to 1. That got the model running but it was extremely slow (processed ~16,000 files after 24 hours). I have 16GB DDR4 RAM.

I eventually got the job done by shifting to a GPU setup, but this error popped up on the other machine as well when I tried to run it on its cpu.

**Comment by adefossez** [comment]
But was it working for any value beyond 1 ? I could just be that you run out of memory and some of the workers died.

Also, what OS are you on ?

**Comment by HarisNaveed17** [comment]
It wasn't working for any value of num_workers other than 1. 
I'm on Ubuntu 18.04.5 LTS.

**Comment by adefossez** [comment]
In your log the `Killed` line indicates for some reason the OS killed one of the process. You can try to obtain the reason with `dmesg -T| grep -E -i -B100 'killed process'` just after having run the `enhance` command (from https://stackoverflow.com/questions/726690/what-killed-my-process-and-why)

I would try with `--num_workers=2`. You can also try to pass `--streaming`. I suspect some out of memory error but I can't be sure without more information.
